
echo Building live-v3...
docker build live-v3 -t polympiads/hc2/live-v3

echo Building stream-admin...
docker build stream-admin -t polympiads/hc2/stream-admin

echo Building clics-api...
docker build clics-api -t polympiads/hc2/clics-api

echo Building balloons...
docker build balloons -t polympiads/hc2/balloons
